// src/lib/components/ui/date-picker.svelte
<script lang="ts">
	import type { DateValue } from '@internationalized/date';

	import { DateFormatter, getLocalTimeZone } from '@internationalized/date';
	import { buttonVariants } from '$lib/components/ui/button/index';
	import { Calendar } from '$lib/components/ui/calendar/index';
	import * as Popover from '$lib/components/ui/popover/index';
	import { cn } from '$lib/utils';
	import CalendarIcon from 'lucide-svelte/icons/calendar';

	type Props = {
		onOpen?: (e: MouseEvent) => void;
		onChange?: (value: DateValue | undefined) => void;
		isOpen?: boolean;
		value: DateValue | undefined;
	};

	const df = new DateFormatter('en-US', {
		dateStyle: 'long'
	});

	// let value = $state<DateValue | undefined>();
	let contentRef = $state<HTMLElement | null>(null);

	let {
		onOpen,
		onChange,
		isOpen = $bindable(false),
		value = $bindable(undefined)
	}: Props = $props();

	$effect(() => {
		onChange?.(value);
	});
</script>

<Popover.Root bind:open={isOpen}>
	<Popover.Trigger
		class={cn(
			buttonVariants({
				variant: 'outline',
				class: 'justify-start text-left font-normal',
				size: 'sm'
			}),
			!value && 'text-muted-foreground'
		)}
		onclick={(e) => {
			onOpen?.(e);
		}}
	>
		<CalendarIcon />
		{value ? df.format(value.toDate(getLocalTimeZone())) : 'Pick a date'}
	</Popover.Trigger>
	<Popover.Content bind:ref={contentRef} class="w-auto p-0">
		<Calendar type="single" bind:value />
	</Popover.Content>
</Popover.Root>

// components/ui/date-picker.tsx
"use client";

import * as React from "react";
import { format } from "date-fns";
import { Calendar as CalendarIcon } from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import {
	Popover,
	PopoverContent,
	PopoverTrigger,
} from "@/components/ui/popover";
import { useTimestamp } from "@/lib/nuqs/use-timestamp";

export function DatePicker() {
	const { date, setDate } = useTimestamp();

	return (
		<Popover>
			<PopoverTrigger asChild>
				<Button
					variant={"outline"}
					className={cn(
						"w-[280px] justify-start text-left font-normal",
						!date && "text-muted-foreground"
					)}
				>
					<CalendarIcon className="mr-2 h-4 w-4" />
					{date ? format(date, "PPP") : <span>Pick a date</span>}
				</Button>
			</PopoverTrigger>
			<PopoverContent className="w-auto p-0">
				<Calendar
					mode="single"
					selected={date}
					onSelect={(selectedDate) => selectedDate && setDate(selectedDate)}
					initialFocus
				/>
			</PopoverContent>
		</Popover>
	);
}
